modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/luxmiyu/anything/issues"
license = "MIT"

[[mods]]
modId = "anything"
version = "${version}"
displayName = "Anything"
authors = "luxmiyu"
description = '''
Create tools and armor out of any block! This mod adds 3800+ tools and armor pieces to the game, for each of the blocks in the game.
'''
#logoFile = ""

[[dependencies.anything]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anything]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anything]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

#[[mixins]]
#config = "anything.mixins.json"
